# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QWidget)
import mvts_analyzer.res.app_resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1710, 957)
        icon = QIcon()
        icon.addFile(u":/Icons/icons/mainwin.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionPython_Code = QAction(MainWindow)
        self.actionPython_Code.setObjectName(u"actionPython_Code")
        icon1 = QIcon()
        icon1.addFile(u":/Icons/icons/Other Icons/python-logo-only.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPython_Code.setIcon(icon1)
        self.actionFilter = QAction(MainWindow)
        self.actionFilter.setObjectName(u"actionFilter")
        self.actionFilter.setEnabled(False)
        icon2 = QIcon()
        icon2.addFile(u":/Icons/icons/Custom Icons/filter.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFilter.setIcon(icon2)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave.setCheckable(False)
        self.actionSave.setEnabled(False)
        icon3 = QIcon()
        icon3.addFile(u":/Icons/icons/Tango Icons/actions/document-save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        icon4 = QIcon()
        icon4.addFile(u":/Icons/icons/Tango Icons/actions/document-save-as.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_As.setIcon(icon4)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon5 = QIcon()
        icon5.addFile(u":/Icons/icons/Tango Icons/actions/process-stop.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon5)
        self.actionLoad_CES_Network = QAction(MainWindow)
        self.actionLoad_CES_Network.setObjectName(u"actionLoad_CES_Network")
        self.actionLoad_CES_Local_SQL = QAction(MainWindow)
        self.actionLoad_CES_Local_SQL.setObjectName(u"actionLoad_CES_Local_SQL")
        self.actionLoad_CES_Local_SQL.setEnabled(False)
        self.actionLive_Window = QAction(MainWindow)
        self.actionLive_Window.setObjectName(u"actionLive_Window")
        self.actionLive_Window.setEnabled(True)
        self.actionLoad_From_File = QAction(MainWindow)
        self.actionLoad_From_File.setObjectName(u"actionLoad_From_File")
        icon6 = QIcon()
        icon6.addFile(u":/Icons/icons/Tango Icons/actions/document-open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLoad_From_File.setIcon(icon6)
        self.actionSave_Figure_As = QAction(MainWindow)
        self.actionSave_Figure_As.setObjectName(u"actionSave_Figure_As")
        self.actionSave_Figure_As.setIcon(icon4)
        self.actionCopy_Figure_To_Clipboard = QAction(MainWindow)
        self.actionCopy_Figure_To_Clipboard.setObjectName(u"actionCopy_Figure_To_Clipboard")
        icon7 = QIcon()
        icon7.addFile(u":/Icons/icons/Tango Icons/actions/edit-copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy_Figure_To_Clipboard.setIcon(icon7)
        self.actionDelete_label = QAction(MainWindow)
        self.actionDelete_label.setObjectName(u"actionDelete_label")
        self.actionDelete_label.setEnabled(False)
        self.actionRename_Label = QAction(MainWindow)
        self.actionRename_Label.setObjectName(u"actionRename_Label")
        self.actionOpenMergeLabelColumnWindow = QAction(MainWindow)
        self.actionOpenMergeLabelColumnWindow.setObjectName(u"actionOpenMergeLabelColumnWindow")
        self.actionOpenMergeLabelColumnWindow.setShortcutVisibleInContextMenu(True)
        self.actionAppend_From_File = QAction(MainWindow)
        self.actionAppend_From_File.setObjectName(u"actionAppend_From_File")
        self.actionAppend_From_File.setEnabled(True)
        icon8 = QIcon()
        icon8.addFile(u":/Icons/icons/Custom Icons/append-from-file.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAppend_From_File.setIcon(icon8)
        self.actiona = QAction(MainWindow)
        self.actiona.setObjectName(u"actiona")
        self.actionApply_Python_File_None = QAction(MainWindow)
        self.actionApply_Python_File_None.setObjectName(u"actionApply_Python_File_None")
        self.actionApply_Python_File_None.setEnabled(False)
        self.actionOpen_View_Copy = QAction(MainWindow)
        self.actionOpen_View_Copy.setObjectName(u"actionOpen_View_Copy")
        self.actionUnhide_All = QAction(MainWindow)
        self.actionUnhide_All.setObjectName(u"actionUnhide_All")
        self.actionHide_Selection = QAction(MainWindow)
        self.actionHide_Selection.setObjectName(u"actionHide_Selection")
        self.actionHide_All_But_Selection = QAction(MainWindow)
        self.actionHide_All_But_Selection.setObjectName(u"actionHide_All_But_Selection")
        self.actionSwitch_Hidden = QAction(MainWindow)
        self.actionSwitch_Hidden.setObjectName(u"actionSwitch_Hidden")
        self.actionSave_Not_Hidden_Only_As = QAction(MainWindow)
        self.actionSave_Not_Hidden_Only_As.setObjectName(u"actionSave_Not_Hidden_Only_As")
        icon9 = QIcon()
        icon9.addFile(u":/Icons/icons/Custom Icons/save_view.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_Not_Hidden_Only_As.setIcon(icon9)
        self.actionSave_Selection_As = QAction(MainWindow)
        self.actionSave_Selection_As.setObjectName(u"actionSave_Selection_As")
        self.actionSave_Selection_As.setCheckable(False)
        self.actionSave_Selection_As.setEnabled(True)
        icon10 = QIcon()
        icon10.addFile(u":/Icons/icons/Custom Icons/save_selection.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_Selection_As.setIcon(icon10)
        self.actionSave_View_As = QAction(MainWindow)
        self.actionSave_View_As.setObjectName(u"actionSave_View_As")
        self.actionSave_View_As.setEnabled(False)
        self.actionSave_View_As.setIcon(icon9)
        self.actionReplot = QAction(MainWindow)
        self.actionReplot.setObjectName(u"actionReplot")
        self.actionReplot_View = QAction(MainWindow)
        self.actionReplot_View.setObjectName(u"actionReplot_View")
        self.actionReplot_View_FFT = QAction(MainWindow)
        self.actionReplot_View_FFT.setObjectName(u"actionReplot_View_FFT")
        self.actionSelect_All = QAction(MainWindow)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionReset_To_Default = QAction(MainWindow)
        self.actionReset_To_Default.setObjectName(u"actionReset_To_Default")
        self.actionReset_View_Settings = QAction(MainWindow)
        self.actionReset_View_Settings.setObjectName(u"actionReset_View_Settings")
        self.actionReset_Domain = QAction(MainWindow)
        self.actionReset_Domain.setObjectName(u"actionReset_Domain")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1710, 22))
        self.menuApply = QMenu(self.menubar)
        self.menuApply.setObjectName(u"menuApply")
        self.menuPython_File2 = QMenu(self.menuApply)
        self.menuPython_File2.setObjectName(u"menuPython_File2")
        self.menuHide = QMenu(self.menuApply)
        self.menuHide.setObjectName(u"menuHide")
        icon11 = QIcon()
        icon11.addFile(u":/Icons/icons/Custom Icons/view.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menuHide.setIcon(icon11)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFigure = QMenu(self.menuFile)
        self.menuFigure.setObjectName(u"menuFigure")
        icon12 = QIcon()
        icon12.addFile(u":/Icons/icons/Tango Icons/mimetypes/image-x-generic.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menuFigure.setIcon(icon12)
        self.menuLoad = QMenu(self.menuFile)
        self.menuLoad.setObjectName(u"menuLoad")
        self.menuLoad.setIcon(icon6)
        self.menuSave_Special = QMenu(self.menuFile)
        self.menuSave_Special.setObjectName(u"menuSave_Special")
        self.menuSave_Special.setGeometry(QRect(463, 178, 174, 98))
        icon13 = QIcon()
        icon13.addFile(u":/Icons/icons/Custom Icons/save-special.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menuSave_Special.setIcon(icon13)
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuLabeler_2 = QMenu(self.menuTools)
        self.menuLabeler_2.setObjectName(u"menuLabeler_2")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuUpdate = QMenu(self.menuView)
        self.menuUpdate.setObjectName(u"menuUpdate")
        self.menuReset = QMenu(self.menuView)
        self.menuReset.setObjectName(u"menuReset")
        self.menuPython_File = QMenu(self.menubar)
        self.menuPython_File.setObjectName(u"menuPython_File")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuApply.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPython_File.menuAction())
        self.menuApply.addAction(self.actionPython_Code)
        self.menuApply.addAction(self.menuPython_File2.menuAction())
        self.menuApply.addSeparator()
        self.menuApply.addAction(self.actionFilter)
        self.menuApply.addAction(self.menuHide.menuAction())
        self.menuPython_File2.addAction(self.actionApply_Python_File_None)
        self.menuHide.addAction(self.actionUnhide_All)
        self.menuHide.addAction(self.actionHide_Selection)
        self.menuHide.addAction(self.actionHide_All_But_Selection)
        self.menuHide.addAction(self.actionSwitch_Hidden)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.menuSave_Special.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuFigure.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFigure.addAction(self.actionSave_Figure_As)
        self.menuFigure.addAction(self.actionCopy_Figure_To_Clipboard)
        self.menuLoad.addAction(self.actionLoad_From_File)
        self.menuLoad.addAction(self.actionAppend_From_File)
        self.menuSave_Special.addAction(self.actionSave_Not_Hidden_Only_As)
        self.menuSave_Special.addAction(self.actionSave_Selection_As)
        self.menuTools.addAction(self.actionOpenMergeLabelColumnWindow)
        self.menuTools.addAction(self.menuLabeler_2.menuAction())
        self.menuLabeler_2.addAction(self.actionRename_Label)
        self.menuView.addAction(self.actionOpen_View_Copy)
        self.menuView.addAction(self.menuUpdate.menuAction())
        self.menuView.addAction(self.menuReset.menuAction())
        self.menuUpdate.addAction(self.actionReplot)
        self.menuUpdate.addAction(self.actionReplot_View)
        self.menuUpdate.addAction(self.actionReplot_View_FFT)
        self.menuReset.addAction(self.actionReset_Domain)
        self.menuReset.addAction(self.actionReset_View_Settings)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Data Analysis", None))
        self.actionPython_Code.setText(QCoreApplication.translate("MainWindow", u"Python Code...", None))
#if QT_CONFIG(shortcut)
        self.actionPython_Code.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.actionFilter.setText(QCoreApplication.translate("MainWindow", u"Filter...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
#if QT_CONFIG(tooltip)
        self.actionSave_As.setToolTip(QCoreApplication.translate("MainWindow", u"Load data from a local file (.pkl) ", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoad_CES_Network.setText(QCoreApplication.translate("MainWindow", u"Load From CES (Network)", None))
#if QT_CONFIG(tooltip)
        self.actionLoad_CES_Network.setToolTip(QCoreApplication.translate("MainWindow", u"Load CES over network, use load from SQL whenever possible as that function is faster", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad_CES_Local_SQL.setText(QCoreApplication.translate("MainWindow", u"Load From CES (Local SQL)", None))
#if QT_CONFIG(tooltip)
        self.actionLoad_CES_Local_SQL.setToolTip(QCoreApplication.translate("MainWindow", u"Load CES data from local SQL database (is preferred over via network in most cases)", None))
#endif // QT_CONFIG(tooltip)
        self.actionLive_Window.setText(QCoreApplication.translate("MainWindow", u"Live Window", None))
        self.actionLoad_From_File.setText(QCoreApplication.translate("MainWindow", u"Load From File", None))
#if QT_CONFIG(tooltip)
        self.actionLoad_From_File.setToolTip(QCoreApplication.translate("MainWindow", u"Load dataframe from file", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionLoad_From_File.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_Figure_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.actionCopy_Figure_To_Clipboard.setText(QCoreApplication.translate("MainWindow", u"Copy to Clipboard", None))
        self.actionDelete_label.setText(QCoreApplication.translate("MainWindow", u"Delete Label", None))
        self.actionRename_Label.setText(QCoreApplication.translate("MainWindow", u"Label Renamer", None))
#if QT_CONFIG(shortcut)
        self.actionRename_Label.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+3", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenMergeLabelColumnWindow.setText(QCoreApplication.translate("MainWindow", u"Column Editor", None))
#if QT_CONFIG(shortcut)
        self.actionOpenMergeLabelColumnWindow.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+2", None))
#endif // QT_CONFIG(shortcut)
        self.actionAppend_From_File.setText(QCoreApplication.translate("MainWindow", u"Append From File", None))
#if QT_CONFIG(shortcut)
        self.actionAppend_From_File.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actiona.setText(QCoreApplication.translate("MainWindow", u"a", None))
        self.actionApply_Python_File_None.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.actionOpen_View_Copy.setText(QCoreApplication.translate("MainWindow", u"Open copy...", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_View_Copy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionUnhide_All.setText(QCoreApplication.translate("MainWindow", u"Unhide All", None))
#if QT_CONFIG(shortcut)
        self.actionUnhide_All.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionHide_Selection.setText(QCoreApplication.translate("MainWindow", u"Hide Selection", None))
#if QT_CONFIG(shortcut)
        self.actionHide_Selection.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionHide_All_But_Selection.setText(QCoreApplication.translate("MainWindow", u"Hide All But Selection", None))
#if QT_CONFIG(shortcut)
        self.actionHide_All_But_Selection.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionSwitch_Hidden.setText(QCoreApplication.translate("MainWindow", u"Switch Hidden", None))
#if QT_CONFIG(shortcut)
        self.actionSwitch_Hidden.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_Not_Hidden_Only_As.setText(QCoreApplication.translate("MainWindow", u"Save Visible As...", None))
#if QT_CONFIG(tooltip)
        self.actionSave_Not_Hidden_Only_As.setToolTip(QCoreApplication.translate("MainWindow", u"Save all datapoints that are not hidden", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave_Selection_As.setText(QCoreApplication.translate("MainWindow", u"Save Selection As...", None))
        self.actionSave_View_As.setText(QCoreApplication.translate("MainWindow", u"Save View As...", None))
        self.actionReplot.setText(QCoreApplication.translate("MainWindow", u"Replot", None))
#if QT_CONFIG(shortcut)
        self.actionReplot.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionReplot_View.setText(QCoreApplication.translate("MainWindow", u"Replot View", None))
#if QT_CONFIG(shortcut)
        self.actionReplot_View.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionReplot_View_FFT.setText(QCoreApplication.translate("MainWindow", u"Replot View FFT", None))
        self.actionSelect_All.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
        self.actionReset_To_Default.setText(QCoreApplication.translate("MainWindow", u"Reset To Default", None))
        self.actionReset_View_Settings.setText(QCoreApplication.translate("MainWindow", u"Reset All View Settings", None))
        self.actionReset_Domain.setText(QCoreApplication.translate("MainWindow", u"Reset Domain", None))
#if QT_CONFIG(shortcut)
        self.actionReset_Domain.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+R", None))
#endif // QT_CONFIG(shortcut)
        self.menuApply.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuPython_File2.setTitle(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.menuHide.setTitle(QCoreApplication.translate("MainWindow", u"Hide", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuFigure.setTitle(QCoreApplication.translate("MainWindow", u"Figure", None))
        self.menuLoad.setTitle(QCoreApplication.translate("MainWindow", u"Load", None))
        self.menuSave_Special.setTitle(QCoreApplication.translate("MainWindow", u"Save Special", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuLabeler_2.setTitle(QCoreApplication.translate("MainWindow", u"Labeler", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuUpdate.setTitle(QCoreApplication.translate("MainWindow", u"Update", None))
        self.menuReset.setTitle(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.menuPython_File.setTitle(QCoreApplication.translate("MainWindow", u"Apply", None))
    # retranslateUi

